-- TABLE TO RECORD ALL VIOLATIONS OF THE ACCESS POLICY
-- This will store: username, time of attempt, and what action was attempted
CREATE TABLE auca_error_log (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50),
    attempt_time  DATE,
    attempted_action VARCHAR2(20),
    reason        VARCHAR2(200)
);
