-- MAIN TABLE WHERE NORMAL DATA IS STORED
-- Users should only be able to insert/update records during allowed days and hours
CREATE TABLE auca (
    record_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50),
    action_time    DATE DEFAULT SYSDATE,
    data_value     VARCHAR2(100)
);
